name: Build React App
on:
  push:
    branches:
      - master
jobs:
  build_react:
    runs-on: ubuntu-latest
    name: Build React App
    steps:
      - uses: actions/checkout@v2
      - id: Build-React-App
        uses: BitDEVil2K16/ReactPagesAction@1.0.0
        with:
          username: 'kragosh'
          reponame: 'sector-racing-view'
          token: ${{ secrets.GITHUB_TOKEN }}